name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run PR Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          node -e "
          import('./dist/review/review/review.service.js').then(async ({ ReviewService }) => {
            const service = new ReviewService();
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const review = await service.reviewPR(owner, repo, process.env.PR_NUMBER, process.env.GITHUB_TOKEN);
            console.log(review);
          });"
